HeavyIonAnalysis/AnalysisTree

CMakeLists.txt, core/CMakeLists.txt, infra/CMakeLists.txt
I made few changes in CMake to get better support of AnalysisTree as a subproject. 
- structure of include directories is reproduced in CMAKE_BINARY_DIR. Now user can include AnalysisTree headers in the same way for external installation of the AnalysisTree and for temporary build in case AnalysisTree is built using new CMake feature FetchContent or using Git-submodules + add_subdirectory.
- add support of modern CMake
=> Cmake improvement

core/CMakeLists.txt, core/Constants.hpp
Get rid of the map of codes and masses, replaced by TDataBasePDG. 
Runtime error in case if the particle is not found.
=> More secure way to get mass of a particle

core/Configuration.hpp, infra/TreeReader.hpp
After few tests no showstopping issues appeared.
AnalysisTree::Configuration::GetLastId is mocked with exception and should not be used anymore.
=> Release 1.0 fix 57

core/EventHeader.hpp
Avoid crash with id field when CopyContent() of EventHeader.
=> not try to rewrite EventHeader's id

infra/PlainTreeFiller.cpp
There is a dot in branchname of AnalysisTree (what is correct according to ROOT officials), but when converting it to a plain tree it leads to problems with reading plain root tree with python. Therefore dot '.' in branchname was replaced with underscore '_'. (I am not sure that replacing is done in the best place, but it works).
=> avoid . in branchname of plaintree

infra-1.0/CMakeLists.txt
Find headers correctly after moving them from CMAKE_BINARY_DIR/include to CMAKE_CURRENT_BINARY_DIR (v2.2.6 - v2.2.7)
=> adapt infra-1.0 to v2.2.7

core/Configuration.cpp, core/Configuration.hpp, infra/Chain.cpp
When creating Chain from the vector of filelists, the resulting Configuration did not contain Matchings from all the files except of 0-th one. This bug was fixed.
=> fix bug with ignoring matchings in configs>0 in filelist

infra/AnalysisEntry.cpp, infra/AnalysisEntry.hpp, infra/BranchChannel.hpp, infra/Cuts.cpp, infra/Cuts.hpp, infra/SimpleCut.cpp, infra/SimpleCut.hpp, infra/Variable.cpp, infra/Variable.hpp
Enabled operating AT::Variable (e.g. AtQA task or Cuts etc.) consisting from any number of EventHeader branches and up to 2 channelized (Track, Particle, Hit) branches.
=> Operate AT::Variable from >2 branches

infra/Chain.cpp, infra/Chain.hpp, infra/TaskManager.cpp
When AT::Infra::TaskManager was initialized with vector of filelists (via friending), and the output chain was created in Copy mode, then friended tree caused errors (non-fatal, but anyway) when opening the output root-file.
Now this problem is fixed by explicit removal of friended trees from the output chain and friended tree branches from the output configuration.
=> Friend Chain

infra/BranchChannel.cpp, infra/Field.cpp
There is a possibility to create a Variable "Ones" (e.g. when filling the multiplicity of tracks etc). The field corresponding to it does not exist and thus does not belong to any type (float, int, bool). In the current implementation it was implicitly realized in **switch** operator, however in different optimization modes (Debug vs Release) the behavior was different, and maybe undefined.
This PR fixes this bug, explicitly operating the case of quasi-field "Ones".
=> fix bug when 'ones' field used in Variable

infra/AnalysisEntry.hpp, infra/Variable.cpp, infra/Variable.hpp
1. Provide a function for IfEmptyVariableConvertToOnes.
2. Additionally fix bug when a reference (argument) variable is constructed from several branches, and GetBranchName() is not allowed.
=> provide a function for IfEmptyVariableConvertToOnes

CMakeLists.txt, infra/AnalysisTask.cpp
For ATQA: split entries if they differ with weights (otherwise if there are two similar entries which differ in weights only, they are overwritten).
=> Entries weights

core/BranchConfig.cpp, core/BranchConfig.hpp, infra/AnalysisEntry.cpp, infra/AnalysisEntry.hpp, infra/Branch.cpp, infra/Branch.hpp, infra/BranchChannel.cpp, infra/BranchChannel.hpp, infra/Chain.cpp, infra/Chain.hpp, infra/Cuts.cpp, infra/Field.cpp, infra/PlainTreeFiller.cpp, infra/SimpleCut.cpp, infra/TaskManager.cpp, infra/Variable.cpp
Add features in infra which will allow for branches post-processing, e.g. merging content of two branches (which have matching) into a single one.
=> Branchmagic

CMakeLists.txt, cmake/AnalysisTreeHashWriter.sh
Following PR [#126](https://github.com/HeavyIonAnalysis/AnalysisTree/pull/126) 
If ANALYSIS_TREE_COMMIT_ORIGINAL variable is FALSE (i.e. there were changes since last commit and git status returns non-empty output), the git diff output is saved in .patch format and propagated into the install/bin directory.
=> Diff Patch into install/bin

cmake/AnalysisTreeConfig.sh.in, cmake/AnalysisTreeHashWriter.sh, infra/TaskManager.cpp, infra/TaskManager.hpp
Make optional creating a new event in each call TaskManager::Exec() that will allow to create a new entry for each channel (usually in AnalysisTree entry <-> event).
=> Channel -> entry plaining

CMakeLists.txt
bugfix of ATHash generating in case when AT is an external package:
CMAKE_SOURCE_DIR which is location of CMakeLists.txt of the global package is replaced with CMAKE_CURRENT_SOURCE_DIR which is location of CMakeLists.txt of AnalysisTree when it is external
=> ATHashWriter bugfix

CMakeLists.txt
bugfix of ATHash generating in case when AT is an external package * 2
=> ATHashWriter bugfix * 2

core/BranchConfig.cpp, core/BranchConfig.hpp, core/Constants.hpp, core/Particle.cpp, core/Particle.hpp, core/Track.cpp, core/Track.hpp, infra/TaskManager.cpp, infra/TaskManager.hpp
1. Added charge field for Track. For daughter class Particle it works in the same way as mass field - linked to the PDG code unless user explicitly sets specific value different from table one.
2. In order to avoid a conflict of field names an additional check is implemented - if one tries to add a field with already existing name (both default or user-defined), an error will be thrown.
Note: In some pieces of code based on AnalysisTree (e.g. CbmRoot interface, PFSimple, Pid etc) the charge could be set as a user-defined field. Now it should be fixed, and a default field should be used. Check described in item (2) will help to localize these places.
=> Charge field

core/BranchConfig.cpp, core/BranchConfig.hpp
1. Enabled removing of user-defined fields from the config of the output branch (can be useful in AnalysisTree post-processing tasks such as Pid, Centrality, BranchWizard etc.).
_Note: this feature was not tested extensively, only basic checks were done. So you are welcome to test it, and before that use feature carefully :)_
2. Fixed bug introduced in PR [#125 ](https://github.com/HeavyIonAnalysis/AnalysisTree/pull/125): variable 'matching_case' was added each time when EventHeader branch was attached to the output BranchConfig, that was not OK. Now it is fixed.
=> Fields removal

core/Constants.hpp, infra/CMakeLists.txt, infra/HelperFunctions.hpp
1. Added a header for functions which are often used in AnalysisTree based macros and ATQA tasks in order to avoid their repetition in every new piece of code. Currently 2 functions are present, however it can be extended.
2. Added a constant `HugeNumber` for effective cuts switching off (releasing).
=> HelperFunctions

examples/CMakeLists.txt, examples/UserTaskRead.cpp, examples/UserTaskWrite.cpp, examples/run_read_task.cpp, examples/run_write_task.cpp, infra/Branch.hpp
1. `examples` directory brought to more order. Now one can easily add new AT-based tasks by placing the `.cpp` file into `examples` directory and adding a proper name in `examples/CMakeLists.txt`, field `EXECUTABLES`.
2. Minor cosmetic changes:
- avoid deprecated function `Chain::GetBranch() `usage;
- provide more precise and informative output in `Branch::CheckFrozen()` and `Branch::CheckMutable()` functions.
=> Enable AT tasks running from examples directory

infra/PlainTreeFiller.cpp, infra/PlainTreeFiller.hpp
See PR https://github.com/HeavyIonAnalysis/AnalysisTree/pull/111, now the set of all default fields (with negative ids) can be excluded from conversion into a plain tree.
=> Enable PlainTreeFiller::SetFieldsToIgnore() for all default fields

infra/Cuts.cpp, infra/Cuts.hpp, infra/HelperFunctions.hpp, infra/SimpleCut.hpp, infra/TaskManager.cpp
Added functions `Cuts::AddCut()` and` Cuts::AddCuts()` which allow for adding `SimpleCut(`s) to already existing `Cuts` object (no need to create `Cuts` object again).
Tried to enable `Cuts` constructon with variadic list of `SimpleCut`s however not succeed yet (the constructor hangs when called). To be fixed.
=> Extend possible ways of Cuts construction: AddCut(s)

core/Particle.test.cpp, infra/Chain.cpp, infra/Cuts.hpp, infra/HelperFunctions.hpp, infra/SimpleCut.cpp, infra/SimpleCut.hpp, infra/SimpleCut.test.cpp
**Major change:**
Before `SimpleCut` comparison (`==` operator) was done in the following way: if their names and lists of variables coincide the `SimpleCut`s are assumed to be equal. And the logic of the `SimpleCut` implemented in the function object (lambda function) was not compared. It lead to a bug when using AnalysisTreeQA package: because of false equality of `Cuts` the histograms supposed to be built with different cuts were built with the same - that one which was declared first.
Now this issue is partially addressed in the following way:
each `SimpleCut` created as `EqualsCut` or `RangeCut` has a hash generated from concatenation of its name, list of variables and numbers to be cutted. If two `SimpleCut`s have different hashes they are assumed non-equal. However if the …
=> Improve SimpleCut comparison

infra/GenericContainerFiller.cpp, infra/GenericContainerFiller.hpp, infra/PlainTreeFiller.cpp, infra/PlainTreeFiller.hpp
1. Enabled `GenericContainerFiller` run based on several plain root files written in the filelist.
2. In `PlainTreeFiller` write **float**, **int** and **bool** fields from the AnalysisTree into plain branches of corresponding type (before all of them were float).
3. Cosmetics.
=> Maintain GenericContainer- and PlainTreeFiller
